// <auto-generated />
using System.Threading;
using System.Threading.Tasks;
using Intercessor.Abstractions;
using FluentValidation;

namespace TestApi.Commands;

public class CreateUserCommandValidator: AbstractValidator<CreateUserCommand>
{
    public CreateUserCommandValidator()
    {
        RuleFor(x => x.Name).NotEmpty().NotNull();
    }
}