// <auto-generated />
using System.Threading;
using System.Threading.Tasks;
using Intercessor.Abstractions;
using TestApi.IntegrationEvents;
using Transponder.Core.Abstractions;

namespace TestApi.Commands;

public sealed class CreateUserCommandHandler : ICommandHandler<CreateUserCommand>
{
    private readonly ILogger<CreateUserCommandHandler> _logger;
    
    public CreateUserCommandHandler(ILogger<CreateUserCommandHandler> logger)
    {
        _logger = logger;
    }

    public async Task HandleAsync(CreateUserCommand request, CancellationToken cancellationToken = default)
    {
        await Task.CompletedTask;
    }
}