// <auto-generated />
using System.Threading;
using System.Threading.Tasks;
using Intercessor.Abstractions;

namespace TestApi.Commands;

public sealed class UpdateUserCommandHandler : ICommandHandler<UpdateUserCommand, TestApi.Dtos.UserDto>
{
    public async Task<TestApi.Dtos.UserDto> HandleAsync(UpdateUserCommand request, CancellationToken cancellationToken = default)
    {
        // TODO: Implement logic
        return await Task.FromResult(new TestApi.Dtos.UserDto("TEST"));
    }
}