// <auto-generated />
using System.Threading;
using System.Threading.Tasks;
using Intercessor.Abstractions;

namespace TestApi.Queries;

public sealed class GetUserQueryHandler : IQueryHandler<GetUserQuery, TestApi.Dtos.UserDto>
{
    public async Task<TestApi.Dtos.UserDto> HandleAsync(GetUserQuery request, CancellationToken cancellationToken = default)
    {
        // TODO: Implement logic
        return await Task.FromResult(new TestApi.Dtos.UserDto("TEST"));
    }
}