// <auto-generated />
using System.Threading;
using System.Threading.Tasks;
using Intercessor.Abstractions;
using FluentValidation;

namespace TestApi.Queries;

public class GetUserQueryValidator: AbstractValidator<GetUserQuery>
{
    public GetUserQueryValidator()
    {
    }
}