// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

using Transponder.Persistence.EntityFramework;
using Transponder.Persistence.EntityFramework.PostgreSql;

#nullable disable

namespace Transponder.Persistence.EntityFramework.PostgreSql.Migrations;

[DbContext(typeof(PostgreSqlTransponderDbContext))]
[Migration("20260125000000_AddSagaStateVersion")]
partial class AddSagaStateVersion
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        string schema = null;

        modelBuilder.Entity("Transponder.Persistence.EntityFramework.InboxStateEntity", b =>
            {
                b.Property<Ulid>("MessageId")
                    .HasColumnType("character(26)");

                b.Property<string>("ConsumerId")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<DateTimeOffset>("ReceivedTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTimeOffset?>("ProcessedTime")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("MessageId", "ConsumerId");

                b.ToTable("InboxStates", schema);
            });

        modelBuilder.Entity("Transponder.Persistence.EntityFramework.OutboxMessageEntity", b =>
            {
                b.Property<Ulid>("MessageId")
                    .HasColumnType("character(26)");

                b.Property<Ulid?>("CorrelationId")
                    .HasColumnType("character(26)");

                b.Property<Ulid?>("ConversationId")
                    .HasColumnType("character(26)");

                b.Property<string>("SourceAddress")
                    .HasMaxLength(2048)
                    .HasColumnType("text");

                b.Property<string>("DestinationAddress")
                    .HasMaxLength(2048)
                    .HasColumnType("text");

                b.Property<string>("MessageType")
                    .HasColumnType("text");

                b.Property<string>("ContentType")
                    .HasColumnType("text");

                b.Property<byte[]>("Body")
                    .IsRequired()
                    .HasColumnType("bytea");

                b.Property<string>("Headers")
                    .HasColumnType("jsonb");

                b.Property<DateTimeOffset>("EnqueuedTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTimeOffset?>("SentTime")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("MessageId");

                b.ToTable("OutboxMessages", schema);
            });

        modelBuilder.Entity("Transponder.Persistence.EntityFramework.SagaStateEntity", b =>
            {
                b.Property<Ulid>("CorrelationId")
                    .HasColumnType("character(26)");

                b.Property<string>("StateType")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("text");

                b.Property<string>("StateData")
                    .IsRequired()
                    .HasColumnType("jsonb");

                b.Property<Ulid?>("ConversationId")
                    .HasColumnType("character(26)");

                b.Property<DateTimeOffset>("UpdatedTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Version")
                    .HasColumnType("integer");

                b.HasKey("CorrelationId", "StateType");

                b.HasIndex("ConversationId");

                b.ToTable("SagaStates", schema);
            });

        modelBuilder.Entity("Transponder.Persistence.EntityFramework.ScheduledMessageEntity", b =>
            {
                b.Property<Ulid>("TokenId")
                    .HasColumnType("character(26)");

                b.Property<string>("MessageType")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("text");

                b.Property<string>("ContentType")
                    .HasColumnType("text");

                b.Property<byte[]>("Body")
                    .IsRequired()
                    .HasColumnType("bytea");

                b.Property<string>("Headers")
                    .HasColumnType("jsonb");

                b.Property<DateTimeOffset>("ScheduledTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTimeOffset>("CreatedTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<DateTimeOffset?>("DispatchedTime")
                    .HasColumnType("timestamp with time zone");

                b.HasKey("TokenId");

                b.HasIndex("ScheduledTime", "DispatchedTime");

                b.ToTable("ScheduledMessages", schema);
            });
#pragma warning restore 612, 618
    }
}
