name: Build and Deploy Docker Compose

on:
  push:
    branches:
      - main

jobs:
  Checkout:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Official SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          dotnet-sonarscanner begin \
            /k:"Sol9" \
            /d:sonar.host.url="${SONAR_HOST_URL}" \
            /d:sonar.login="${SONAR_TOKEN}"
          dotnet build .\Sol9.sln
          dotnet-sonarscanner end /d:sonar.login="${SONAR_TOKEN}"
